codecov:
  token: 4d51ca07-e26e-4231-92b5-5d61a106ff5c
  branch: master

coverage:
  precision: 3
  round: nearest
  range: "50...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        branches: null

    patch:
      default:
        target: auto
        branches: null
        threshold: 1%

    changes:
      default:
        branches: null
        threshold: 1%

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: null
  behavior: default
