---
title: "additional vignettes"
author: "Indrajeet Patil"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    toc: true
    warning: FALSE
    message: FALSE
vignette: >
  %\VignetteIndexEntry{additional vignettes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  message = FALSE,
  warning = FALSE,
  comment = "#>"
)
```

# Additional vignettes

Due to constraints on the size of the `R` package, all available vignettes are
only available on the website for this package: <br>
<https://indrajeetpatil.github.io/ggstatsplot/articles/>

## Vignettes for individual functions

  - `ggbetweenstats`:
    (<https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/ggbetweenstats.html>)

  - `ggwithinstats`:
    (<https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/ggwithinstats.html>)

  - `ggcorrmat`:
    (<https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/ggcorrmat.html>)

  - `gghistostats`:
    (<https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/gghistostats.html>)

  - `ggdotplotstats`:
    (<https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/ggdotplotstats.html>)

  - `ggpiestats`:
    (<https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/ggpiestats.html>)

  - `ggscatterstats`:
    (<https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/ggscatterstats.html>)

  - `ggcoefstats`:
    (<https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/ggcoefstats.html>)

  - How to arrange multiple plots in a single plot along with annotations using
    the `combine_plots` helper function:
    (<https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/combine_plots.html>)

## General vignettes

  - Publication describing philosophy and principles behind this package:
    (<https://joss.theoj.org/papers/10.21105/joss.03167>)

  - Frequently Asked Questions (FAQ)-
    (<https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/faq.html>)

  - Interpreting effect sizes for different tests:
    (<https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/effsize_interpretation.html>)

  - Graphic design and statistical reporting principles guiding `ggstatsplot`
    development:
    (<https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/principles.html>)

  - Examples illustrating how to use functional programming package like `purrr`
    to extend `ggstatsplot` functionality-
    (<https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/purrr_examples.html>)

  - Session information:
    (<https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/session_info.html>)

# Presentation

In addition to these vignettes, another quick way to get an overview of this
package is to go through the following slides:
<https://indrajeetpatil.github.io/ggstatsplot_slides/slides/ggstatsplot_presentation.html#1>

# Components of `ggstatsplot`

To make the maintenance and development of `ggstatsplot` more manageable, it is
being broken into smaller pieces. Currently, the package internally relies on
the following packages that manage different aspects of statistical analyses:

## `statsExpressions`

The `statsExpressions` package forms the statistical backend that processes data
and creates dataframes and expressions containing results from statistical
tests.

For more exhaustive documentation for this package, see:
<https://indrajeetpatil.github.io/statsExpressions/>

## `pairwiseComparisons`

The `pairwiseComparisons` package forms the pairwise comparison backend for
creating results that are used to display *post hoc* multiple comparisons
displayed in `ggbetweenstats` and `ggwithinstats` functions.

For more exhaustive documentation for this package, see:
<https://indrajeetpatil.github.io/pairwiseComparisons/>

# Other resources

Few other people have also written about `ggstatsplot` and its usage in their
workflows:
(<https://indrajeetpatil.github.io/ggstatsplot/articles/web_only/other_resources.html>)

# Suggestions

If you find any bugs or have any suggestions/remarks, please file an issue on
`GitHub`: <https://github.com/IndrajeetPatil/ggstatsplot/issues>

