on:
  pull_request:
    branches: [main, master]

name: metadata

jobs:
  metadata:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: devel
          upgrade: 'TRUE'
          extra-packages: |
            local::.
            cboettig/codemeta
            ropensci/cffr

      - name: Generate codemeta metadata
        run: |
          options(crayon.enabled = TRUE)
          codemeta::write_codemeta()
        shell: Rscript {0}

      - name: Generate CFF metadata
        run: |
          options(crayon.enabled = TRUE)
          cffr::cff_write()
        shell: Rscript {0}

      - uses: stefanzweifel/git-auto-commit-action@v4
