---
title: "Benchmarking"
author: "Indrajeet Patil"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_document:
    fig_width: 6
    fig.align: 'center'
    fig.asp: 0.618
    dpi: 300
    toc: true
    toc_depth: 3
    warning: FALSE
    message: FALSE
---

```{r}
#| label = "setup",
#| include = FALSE
options(
  tibble.width = Inf,
  pillar.bold = TRUE,
  pillar.neg = TRUE,
  pillar.subtle_num = TRUE,
  pillar.min_chars = Inf
)

knitr::opts_chunk$set(
  collapse = TRUE,
  dpi = 300,
  out.width = "100%",
  comment = "#>",
  warning = FALSE,
  message = FALSE
)
```

# Introduction

This is mostly to keep track of how the performance of different functions
changes across time.

# `ggbetweenstats`

```{r}
#| label = "ggbetweenstats"

bench::mark(
  ggbetweenstats(
    data = dplyr::filter(
      movies_long,
      genre %in% c("Action", "Action Comedy", "Action Drama", "Comedy")
    ),
    x = mpaa,
    y = length
  )
) %>%
  dplyr::select(-expression)

bench::mark(
  grouped_ggbetweenstats(
    data = dplyr::filter(
      movies_long,
      genre %in% c("Action", "Action Comedy", "Action Drama", "Comedy")
    ),
    x = mpaa,
    y = length,
    grouping.var = genre
  )
) %>%
  dplyr::select(-expression)
```

# `ggwithinstats`

```{r}
#| label = "ggwithinstats"

bench::mark(
  ggwithinstats(
    data = bugs_long,
    x = condition,
    y = desire
  )
) %>%
  dplyr::select(-expression)


bench::mark(
  grouped_ggwithinstats(
    data = bugs_long,
    x = condition,
    y = desire,
    grouping.var = gender
  )
) %>%
  dplyr::select(-expression)
```

# `gghistostats`

```{r}
#| label = "gghistostats"

bench::mark(gghistostats(mtcars, wt, test.value = 3)) %>%
  dplyr::select(-expression)


bench::mark(grouped_gghistostats(mtcars, wt, test.value = 3, grouping.var = am)) %>%
  dplyr::select(-expression)
```

# `ggdotplotstats`

```{r}
#| label = "ggdotplotstats"

bench::mark(ggdotplotstats(
  dplyr::filter(ggplot2::mpg, cyl %in% c("4", "6")),
  cty,
  manufacturer,
  test.value = 15
)) %>%
  dplyr::select(-expression)


bench::mark(
  grouped_ggdotplotstats(
    dplyr::filter(ggplot2::mpg, cyl %in% c("4", "6")),
    cty,
    manufacturer,
    test.value = 15,
    grouping.var = cyl
  )
) %>%
  dplyr::select(-expression)
```

# `ggscatterstats`

```{r}
#| label = "ggscatterstats"

bench::mark(ggscatterstats(mtcars, wt, mpg)) %>%
  dplyr::select(-expression)


bench::mark(grouped_ggscatterstats(mtcars, wt, mpg, grouping.var = am)) %>%
  dplyr::select(-expression)
```

# `ggcorrmat`

```{r}
#| label = "ggcorrmat"

bench::mark(ggcorrmat(iris)) %>%
  dplyr::select(-expression)


bench::mark(grouped_ggcorrmat(iris, grouping.var = Species)) %>%
  dplyr::select(-expression)
```

# `ggpiestats`

```{r}
#| label = "ggpiestats"



bench::mark(ggpiestats(mtcars, cyl)) %>%
  dplyr::select(-expression)


bench::mark(grouped_ggpiestats(mtcars, cyl, grouping.var = am)) %>%
  dplyr::select(-expression)
```

# `ggbarstats`

```{r}
#| label = "ggbarstats"

bench::mark(ggbarstats(ggplot2::mpg, fl, class)) %>%
  dplyr::select(-expression)


bench::mark(grouped_ggbarstats(ggplot2::mpg, fl, class, grouping.var = drv)) %>%
  dplyr::select(-expression)
```

# `ggcoefstats`

```{r}
#| label = "ggcoefstats"
bench::mark(ggcoefstats(stats::lm(formula = wt ~ am * cyl, data = mtcars))) %>%
  dplyr::select(-expression)
```

# Suggestions

If you find any bugs or have any suggestions/remarks, please file an issue on
GitHub: <https://github.com/IndrajeetPatil/ggstatsplot/issues>
