---
title: "other resources to learn about `ggstatsplot`"
author: "Indrajeet Patil"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    fig_width: 6
    fig.align: 'center'
    fig.asp: 0.618
    dpi: 100
    toc: true
    warning: FALSE
    message: FALSE
vignette: >
  %\VignetteIndexEntry{other resources to learn about `ggstatsplot`}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = FALSE
)
```

# Introduction

One of the best resources to learn about functionality afforded by `ggstatsplot`
package is to read the dedicated
[website](https://indrajeetpatil.github.io/ggstatsplot/). A lot of love and work
has gone into writing detailed function documentation and vignettes, and I will
highly recommend you check them out.

But, the website is certainly not the only resource available to learn about
this package, and below are some other resources that might be helpful for you
to learn about `ggstatsplot` package.

# Presentations

  - My own `xaringan` presentation:
    <https://indrajeetpatil.github.io/ggstatsplot_slides/slides/ggstatsplot_presentation.html#1>

# YouTube Videos

## My own talks at online meetings
  
  - [At UseR Oslo meeting](https://www.youtube.com/watch?v=_wCo7rnt6NA)

  - [At R-Ladies Tunis meeting](https://www.youtube.com/watch?v=n-sXeshyVRI)

## Other

### English

  - [Yury Zablotski's review](https://www.youtube.com/watch?v=cNJIMwtLWv0)

  - [Business Science R tips](https://www.youtube.com/watch?v=8Em1bCFBMWg)

  - <https://www.youtube.com/watch?v=aw6HDz9zA1Q>

  - [Serdar Belci's demo](https://www.youtube.com/watch?v=m3uInetiC8w) on how to
    use `ggstatsplot` in `jamovi` GUI software

  - Data pre-processing and analysis in
    [RStudio](https://www.youtube.com/watch?v=IMgv5pc7N7U) and `ggstatsplot`

### Other languages

  - [Pablo Vallejo Medina's demo](https://www.youtube.com/watch?v=6Ds9L4NpRVQ)
    of `ggbetweenstats` (in **Spanish**)

  - [Andre Chocó Cedillos's talk](https://www.youtube.com/watch?v=yDyrgvvWLpc)
    (in **Spanish**)

# Blogs

This is a bit difficult to keep track of. I would recommend just googling it.

# Publications

A list of publications that use `ggstatsplot` can be found in Google Scholar:

<https://scholar.google.com/scholar?hl=en&scisbd=2&as_sdt=0%2C22&q=ggstatsplot&btnG=>

