# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <ggwithinstats>
  # <.grouped_list>
  ".",
  # <ggbarstats>
  # <ggpiestats>
  ".counts",
  # <ggbarstats>
  # <ggpiestats>
  ".label",
  # <ggbarstats>
  ".p.label",
  # <ggwithinstats>
  ".rowid",
  # <.histo_labeller>
  ".x",
  # <ggcoefstats>
  # <ggdotplotstats>
  "conf.high",
  # <ggcoefstats>
  # <ggdotplotstats>
  "conf.low",
  # <descriptive_data>
  # <.cat_counter>
  # <onesample_data>
  "counts",
  # <ggcoefstats>
  "estimate",
  # <.ggsignif_adder>
  "group1",
  # <.ggsignif_adder>
  "group2",
  # <ggbarstats>
  "N",
  # <.ggsignif_adder>
  # <ggcoefstats>
  "p.value",
  # <ggbarstats>
  # <descriptive_data>
  # <ggpiestats>
  "perc",
  # <ggcoefstats>
  "term",
  # <.histo_labeller>
  "var",
  NULL
))
