# defining global variables and functions to appease R CMD Check

utils::globalVariables(
  names = c(
    ".",
    "N",
    "conf.high",
    "conf.low",
    "count",
    "counts",
    "df.error",
    "estimate",
    "group1",
    "group2",
    "isanoutlier",
    "label",
    "median",
    "p.value",
    "parameter",
    "perc",
    "rowid",
    ".rowid",
    "sd",
    "significance",
    "statistic",
    "std.error",
    "term",
    "df",
    ".label",
    ".counts",
    ".p.label",
    "trimmed.mean",
    "group",
    "r.method",
    "r.method.text",
    ".x",
    "var",
    "renderPlot",
    ".f",
    ".fn",
    ".ns",
    "log_e_bf10"
  ),
  package = "ggstatsplot",
  add = FALSE
)
