# defining global variables and functions to appease R CMD Check
#

utils::globalVariables(
  names = c(
    ".",
    "U",
    "V",
    "Z",
    "chi",
    "counts",
    "df",
    "df1",
    "df2",
    "effsize",
    "estimate",
    "eta",
    "omega",
    "perc",
    "cramer",
    "cramer_ci",
    "pvalue",
    "r",
    "rho",
    "xi",
    "y",
    "z_value",
    "italic",
    "rsubtitle",
    "stats_subtitle",
    "chi_subtitle",
    "proptest_subtitle",
    "LL",
    "UL",
    "outlier",
    "outlier.label",
    "proptest_subtitle",
    "significance",
    "..count..",
    "dnorm",
    "mean",
    "median",
    "sd",
    "bf",
    "bf_error"
  ),
  package = "ggstatsplot",
  add = FALSE
)
