# defining global variables and functions to appease R CMD Check

utils::globalVariables(
  names = c(
    ".",
    "..count..",
    "N",
    "conf.high",
    "conf.low",
    "counts",
    "df.error",
    "estimate",
    "group1",
    "group2",
    "isanoutlier",
    "label",
    "median",
    "p.value",
    "parameter",
    "perc",
    "rowid",
    ".rowid",
    "sd",
    "significance",
    "statistic",
    "std.error",
    "term",
    "df",
    ".label",
    ".counts",
    ".p.label",
    "trimmed.mean",
    "group",
    "r.method",
    "r.method.text",
    ".temp",
    "var",
    "renderPlot"
  ),
  package = "ggstatsplot",
  add = FALSE
)
