# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  ".counts", # <ggbarstats>
  "perc", # <ggbarstats>
  ".label", # <ggbarstats>
  ".p.label", # <ggbarstats>
  "N", # <ggbarstats>
  "group1", # <.ggsignif_adder>
  "group2", # <.ggsignif_adder>
  "p.value", # <.ggsignif_adder>
  "term", # <ggcoefstats>
  "p.value", # <ggcoefstats>
  "estimate", # <ggcoefstats>
  "conf.low", # <ggcoefstats>
  "conf.high", # <ggcoefstats>
  ".x", # <.histo_labeller>
  "var", # <.histo_labeller>
  "counts", # <descriptive_data>
  "perc", # <descriptive_data>
  "counts", # <.cat_counter>
  "counts", # <onesample_data>
  ".counts", # <ggpiestats>
  "perc", # <ggpiestats>
  ".label", # <ggpiestats>
  ".", # <ggwithinstats>
  ".rowid", # <ggwithinstats>
  ".", # <.grouped_list>
  NULL
))
