---
title: "Enhancing 'ggplot2' with statistical details: The 'ggstatsplot' approach"
tags:
  - R
  - parametric statistics
  - nonparametric statistics
  - robust statistics
  - Bayesian statistics
  - ggplot2
  - ggplot2-extension
authors:
  - name: Indrajeet Patil
    orcid: 0000-0003-1995-6531
    affiliation: 1
affiliations:
  - name: Center for Humans and Machines, Max Planck Institute for Human Development, Berlin, Germany
citation_author: Patil
date: "`r Sys.Date()`"
bibliography: paper.bib
output: rticles::joss_article
csl: apa.csl
journal: JOSS
link-citations: yes
header-includes:
  - \usepackage{tabularx}
  - \usepackage{booktabs}
  - \usepackage{tikz}
  - \usepackage{float}
---

```{r, warning=FALSE, message=FALSE, echo=FALSE}
# needed libraries
library(ggstatsplot)

# show me all columns
options(tibble.width = Inf)

knitr::opts_chunk$set(
  collapse = TRUE,
  out.width = "100%",
  dpi = 450,
  comment = "#>",
  fig.pos = "H",
  message = FALSE,
  warning = FALSE
)

library(ggstatsplot)
```

# Summary

In a typical exploratory data analysis workflow, data visualization and
statistical modeling are two different phases: visualization informs modeling,
and modeling in its turn can suggest a different visualization method, and so on
and so forth. The central idea of `ggstatsplot` is simple: combine these two
phases into one in the form of graphics with statistical details, which makes
data exploration simpler and faster.

# Statement of Need


# `ggstatsplot` at a glance

# Benefits

This approach- (*a*) avoids errors in statistical reporting, (*b*) highlights
the importance of the effect by providing effect size measures by default, (*c*)
provides an easy way to evaluate *absence* of an effect using Bayesian
framework, (*d*) forces to evaluate statistical assumptions behind chosen
analysis in the context of the underlying data, and is (*e*) easy and (*f*)
simple enough that somebody with little-to-no coding experience can use it
without making an error.

# Licensing and Availability

`ggstatsplot` is licensed under the GNU General Public License (v3.0), with
all source code stored at
[GitHub](https://github.com/IndrajeetPatil/ggstatsplot/), and with a
corresponding issue tracker for bug reporting and feature enhancements. In the
spirit of honest and open science, we encourage requests/tips for fixes, feature
updates, as well as general questions and concerns via direct interaction with
contributors and developers, by [filing an issue](https://github.com/IndrajeetPatil/ggstatsplot/issues). See the
package's [*Contribution Guidelines*](https://github.com/IndrajeetPatil/ggstatsplot/blob/master/.github/CODE_OF_CONDUCT.md).

# Acknowledgements

I would like to acknowledge the support of Mina Cikara, Fiery Cushman, and Iyad
Rahwan during the development of this project. `ggstatsplot` relies heavily
on the [`easystats`](https://github.com/easystats/easystats) ecosystem, a
collaborative project created to facilitate the usage of `R` for statistical
analyses. Thus, I would like to thank the [members of easystats](https://github.com/orgs/easystats/people) as well as the users.

\newpage

# References
