on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: check-readme

jobs:
  check-readme:
    uses: IndrajeetPatil/workflows/.github/workflows/check-readme.yaml@main
    with:
      extra-packages: |
        any::ggstatsplot
        any::ggthemes
