on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: check-no-warnings

jobs:
  check-no-warnings:
    uses: IndrajeetPatil/workflows/.github/workflows/check-no-warnings.yaml@main
