on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: HTML5 check

jobs:
  html-5-check:
    uses: IndrajeetPatil/workflows/.github/workflows/html-5-check.yaml@main
