on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: pkgdown-no-suggests

jobs:
  pkgdown-no-suggests:
    uses: IndrajeetPatil/workflows/.github/workflows/pkgdown.yaml@main
    with:
      no-suggests: true
