on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    uses: IndrajeetPatil/workflows/.github/workflows/pkgdown.yaml@consolidate-r-package-workflows
    permissions:
      contents: write
