on:
  pull_request:
    branches: [main, master]

name: pre-commit

jobs:
  pre-commit:
    uses: IndrajeetPatil/workflows/.github/workflows/pre-commit.yaml@consolidate-r-package-workflows
    permissions:
      contents: write
