on:
  pull_request:
    branches: [main, master]

name: prek

jobs:
  prek:
    uses: IndrajeetPatil/workflows/.github/workflows/pre-commit.yaml@chore/migrate-to-prek
    permissions:
      contents: write
