# R CMD Check is run with the development versions of hard dependencies.
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Trigger once a week at 00:00 on Sunday
    - cron: "0 0 * * SUN"

name: R-CMD-check-devel

jobs:
  R-CMD-check-devel:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "3.1.12.1"

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "devel"
          use-public-rspm: true

      # only download hard deps under active development
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: devel
          upgrade: 'TRUE'
          needs: check
          cache: false
          extra-packages: |
            any::rcmdcheck
            easystats/insight
            easystats/datawizard
            easystats/effectsize
            easystats/parameters
            easystats/performance
            tidyverse/purrr
            tidyverse/dplyr
            tidyverse/tibble
            tidyverse/tidyr

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          upload-results: true
          error-on: '"note"'
