on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check-hard

jobs:
  R-CMD-check-hard:
    uses: IndrajeetPatil/workflows/.github/workflows/R-CMD-check-hard.yaml@consolidate-r-package-workflows
    with:
      extra-packages: any::vdiffr
