on:
  pull_request:
    branches: [main, master]

name: R-CMD-check-hard

jobs:
  R-CMD-check-hard:
    uses: IndrajeetPatil/workflows/.github/workflows/R-CMD-check.yaml@main
    with:
      hard: true
      extra-packages: any::vdiffr any::patrick
