on:
  pull_request:
    branches: [main, master]
    paths: ["**.[rR]", "**.[qrR]md", "**.[rR]markdown", "**.[rR]nw"]

name: style

jobs:
  style:
    uses: IndrajeetPatil/workflows/.github/workflows/style.yaml@main
    permissions:
      contents: write
