on:
  pull_request:
    branches: [main, master]
    paths: ["**.[rR]", "**.[qrR]md", "**.[rR]markdown", "**.[rR]nw"]

name: Style

jobs:
  styler:
    uses: IndrajeetPatil/workflows/.github/workflows/styler.yaml@main
    permissions:
      contents: write
