on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test-coverage-examples

jobs:
  test-coverage-examples:
    uses: IndrajeetPatil/workflows/.github/workflows/test-coverage-examples.yaml@main
    with:
      threshold: 90
