on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test-coverage

jobs:
  test-coverage:
    uses: IndrajeetPatil/workflows/.github/workflows/test-coverage.yaml@main
